tasks:
  - name: Start web server
    init: python -m http.server 8000
  - name: Minimize Terminal
    command: gitpod-cli terminal minimize
  - name: Hide Minimap
    command: gitpod-cli settings set 'editor.minimap.enabled' false

ports:
  - port: 8000
    onOpen: open-preview